import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Meraj - Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <div>{children}</div>
  );
}
