import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/redux/Store/store";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Navbar from "@/components/shared/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Meraj - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      {/* <Provider store={store}> */}
      {/* <QueryClientProvider client={queryClient}> */}
      <body className={`${ubuntu.className} bg-bg1`}>
        <Navbar/>{children}</body>
      {/* </QueryClientProvider> */}
      {/* </Provider> */}
    </html>
  );
}
